version: "3.7"

services:
  mongo:
    hostname: scr_mongo
    container_name: scr_mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo/data/db:/data/db
    command: "mongod --replSet rs0"

  redis:
    hostname: scr_redis
    container_name: scr_redis
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  stan:
    hostname: scr_stan
    container_name: scr_stan
    image: nats-streaming:0.18
    command: "--store FILE --dir /data/queue --max_msgs 0 --max_bytes 0 --max_age 720h --port 4222 --http_port 8222"
    ports:
      - 4222:4222
      - 8222:8222

  minio:
    hostname: scr_minio
    container_name: scr_minio
    image: minio/minio:RELEASE.2020-12-10T01-54-29Z
    command: "server /data"
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
